# Copyright 2022-2024, Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Check copyright

permissions: read-all

on: [pull_request]

jobs:
  check_copyright:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false

    - name: Check copyright
      run: |
        ./check_copyright.sh "origin/$GITHUB_BASE_REF"

