# Copyright 2023-2024 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

name: Rebuild LLVM 16.0

permissions: read-all

on:
  push:
    branches:
      - main
      - '**rebuild_llvm**'
    paths:
      - "llvm_patches/*16_0*"
      - "alloy.py"
      - "superbuild/*"
      - ".github/workflows/rebuild-llvm16.yml"
      - ".github/workflows/reusable.rebuild.yml"
  workflow_dispatch:

jobs:
  llvm16:
    uses: ./.github/workflows/reusable.rebuild.yml
    with:
      version: '16.0'
      full_version: '16.0.6'
      lto: 'ON'
      ubuntu: '22.04'
      vs_generator: 'Visual Studio 16 2019'
      vs_version_str: 'vs2019'
      win_sdk: '10.0.17763.0'
